# Generated by Django 4.2 on 2023-04-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(default='Новая колода', max_length=30, verbose_name='название'),
        ),
    ]
