# Generated by Django 4.2 on 2023-04-14 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('decks', '0005_alter_deck_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='приватная'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='owner',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
    ]
