# Generated by Django 4.2 on 2023-04-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        ("decks", "0006_alter_deck_is_private_alter_deck_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="progress",
            name="card",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="decks",
                to="cards.card",
                verbose_name="карта",
            ),
        ),
        migrations.AlterField(
            model_name="progress",
            name="deck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="decks.deck",
                verbose_name="колода",
            ),
        ),
    ]
