# Generated by Django 4.2 on 2023-04-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decks', '0007_alter_progress_card_alter_progress_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='last_repeated',
            field=models.DateTimeField(null=True, verbose_name='время последнего повторения'),
        ),
    ]
