# Generated by Django 4.2 on 2023-04-20 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_alter_card_examples_alter_card_transcription'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='last_repeated',
            field=models.DateTimeField(null=True, verbose_name='время последнего повторения'),
        ),
    ]
