# Generated by Django 4.2 on 2023-04-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_last_repeated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='last_repeated',
        ),
    ]
